## PyTorch Introduction

### Creating a Tensor

In [1]:
# importing pyTorch
import torch

In [3]:
# creating a scalar
scalar_value = torch.tensor(100)

print(type(scalar_value))

<class 'torch.Tensor'>


In [6]:
# we can use .item() to get the torch object as an int or python object
hundred = scalar_value.item()
print(type(hundred))

<class 'int'>


In [7]:
vector_value = torch.tensor([100, 150])
matrix_value = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_value = torch.tensor([[[1, 2, 3], [4, 5, 6]]])

In [8]:
print(vector_value)
print(matrix_value)
print(tensor_value)

tensor([100, 150])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[1, 2, 3],
         [4, 5, 6]]])


### Creating a random tensor

In [12]:
random_tensor = torch.rand(1, 2, 3, 4)
print(random_tensor)
print(f'Number of dimensions: {random_tensor.ndim}')

tensor([[[[0.6006, 0.9784, 0.4913, 0.8787],
          [0.2012, 0.1660, 0.0232, 0.6378],
          [0.1360, 0.7521, 0.9998, 0.6100]],

         [[0.9615, 0.4006, 0.1630, 0.1037],
          [0.6795, 0.0031, 0.0569, 0.3589],
          [0.2975, 0.1169, 0.7237, 0.6934]]]])
4
